create table if not exists public.typing_runs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  completed_at timestamptz not null,
  device text not null check (device in ('computer', 'mobile')),
  mode text not null check (mode in ('time', 'words', 'quote', 'zen', 'custom')),
  duration integer not null default 30,
  word_count integer not null default 25,
  quote_length text not null default 'medium' check (quote_length in ('short', 'medium', 'long')),
  punctuation boolean not null default true,
  numbers boolean not null default false,
  variant_key text not null default '',
  elapsed_ms integer not null,
  wpm numeric(8, 2) not null,
  raw_wpm numeric(8, 2) not null,
  accuracy numeric(5, 2) not null,
  consistency numeric(5, 2) not null,
  correct integer not null,
  incorrect integer not null,
  extra integer not null,
  missed integer not null,
  fixes integer not null,
  assisted boolean not null default false,
  samples jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, client_id)
);

create index if not exists typing_runs_user_completed_at_idx
  on public.typing_runs (user_id, completed_at desc);

alter table public.typing_runs enable row level security;

revoke all on table public.typing_runs from anon;
grant select, insert, update, delete on table public.typing_runs to authenticated;
grant usage, select on sequence public.typing_runs_id_seq to authenticated;

drop policy if exists "Users can view their own typing runs" on public.typing_runs;
create policy "Users can view their own typing runs"
  on public.typing_runs for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their own typing runs" on public.typing_runs;
create policy "Users can create their own typing runs"
  on public.typing_runs for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own typing runs" on public.typing_runs;
create policy "Users can update their own typing runs"
  on public.typing_runs for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own typing runs" on public.typing_runs;
create policy "Users can delete their own typing runs"
  on public.typing_runs for delete
  to authenticated
  using ((select auth.uid()) = user_id);
